version: '3.4'

services:
  app:
    build: 
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "mysql"
    networks:
      - internal
  web:
    build:
        context: .
        dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    depends_on:
        - "app"
    ports:
        - 80:80
    networks:
      - internal
  mysql:
    container_name: mysql-task2-container
    restart: always
    image: mysql/mysql-server:latest
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
  redis:
    image: redis:latest
    container_name: app_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - internal
networks:
  internal:
    driver: bridge
    name: task2-network

volumes:
    dbdata: